### ISSUE TITLE
Topx Only Interfaces stats shown

### ISSUE THREAD

**Issue by subarusyd** [xmacan/plugin_topx#2]
Hi

Thanks for this amazing plugin. 

i want to be able to show multiple stats on the TopX plugin such as highest CPU , RAM and Temp devices from the network switches i am polling. 

is there a prescripted codes i can use to pull this information in TOPX? basically i am using Cacti for all the network switches polling such as Interface Traffic, CPU, Temp, Fan and Mem monitoring.  Thinking of if there is any helpful stats i can get in Topx related to this rrd data.?!

Thanks

**Comment by subarusyd** [comment]
Also when the TopX tab is clicked the only that shows is "Interface - Traffic" title. i have to click Go everytime to show data and the graph next to it.  Any ideas?

I am using Ubuntu 18.0 LTS server with PHP 7.2 and this github version TopX plugin version

**Comment by xmacan** [comment]
I have written TopX few years ago and there could be a lot of bugs. 

Second problem with Go button - I know about it, but now I cannot reproduce it now. I will look at it soon.

For adding more stats - It is possible and it depends on data sources. Please read HOW_TO_ADD_YOUR_DATA.txt .. or send me which data source you want from this SQL query:
SELECT DISTINCT data_template.id, data_template.name,hash
FROM data_template INNER JOIN data_template_data
ON data_template.id=data_template_data.data_template_id
ORDER BY data_template.name;

**Comment by xmacan** [comment]
Second problem with Go button  - it is solved now. Please install actual version from github

**Comment by subarusyd** [comment]
Thanks So Much. you are the best. It working all good now.. Thanks millions agaign.

**Comment by subarusyd** [comment]
Sorry i was hitting a wall with this sql commands. A bit beyond me. 
Basically i am graphing all the Wireless access points interface traffic with total bandwidth option. 

I wanted to show the Top 5 or Top 10 highest Bandwidth consuming APs sorted by highest bandwidth first including the Traffic bandwith throughput counter as well?! Any ideas if its possible?

Thanks

**Comment by xmacan** [comment]
Highest Bandwidth is little problem. TopX works with data sources and I don't see data source for this. 
TopX Interface traffic could displays similar output. It si traffic_in+traffic_out together. If it isn't good for you, you have to prepare data source similar to console->templates->data source-> interface traffic and next step is described in my first post in this issue. 
Now I'm busy to make new data source and test, sorry

**Comment by subarusyd** [comment]
Thanks a lot

Thats a good reference point to start with

**Comment by xmacan** [comment]
Cacti's dsstats was implemented.  Please try new version

**Comment by xmacan** [comment]
Important - I implemented dsstats and my first post isn't possible use. Now you have two datasource for any interface - in and out direction. Now it isn't possible to sum in and out together.
