### ISSUE TITLE
Traffic larger than 10G

### ISSUE THREAD

**Issue by maxstech** [xmacan/plugin_topx#3]
Hello. 
Traffic larger than 10 Gbps is not displayed
How to fix ?

but on some charts, the traffic does not exceed 10Gb, but the counter is worth 10,000.

![all topx](https://user-images.githubusercontent.com/47040342/59692877-89b38b80-91ee-11e9-844a-4a7655eeaa12.jpg)

db_execute ("INSERT INTO plugin_topx_source (sorting,dt_name,hash,operation,unit,final_operation,final_unit,final_number) values ('desc','Interface - traffic','6632e1e0b58a565c135d7ff90440c335','traffic_in+traffic_out','Bits','/','Mbit','10000000000')");

**Comment by xmacan** [comment]
This Data template is prepared in TopX. Try SQL query:
select dt_name,hash,unit from plugin_topx_source where dt_name like '%Interface%';
+-----------------------------+----------------------------------+----------------+
| dt_name                     | hash                             | unit           |
+-----------------------------+----------------------------------+----------------+
| Interface - Errors/Discards | 36335cd98633963a575b70639cd2fdad | Errors+Discard |
| Interface - traffic         | 6632e1e0b58a565c135d7ff90440c335 | Bits           |
+-----------------------------+----------------------------------+----------------+
2 rows in set (0.00 sec)

If you see 2 returned rows, problem isn't here. 

I haven't 10Gig cards with big traffic like you. Please send me mysqldump of two tables:
plugin_topx_source
plugin_topx_average

**Comment by maxstech** [comment]
command output
select dt_name,hash,unit from plugin_topx_source where dt_name like '%Interface%';
+-----------------------------+----------------------------------+----------------+
| dt_name                     | hash                             | unit           |
+-----------------------------+----------------------------------+----------------+
| Interface - Errors/Discards | 36335cd98633963a575b70639cd2fdad | Errors+Discard |
| Interface - traffic         | 6632e1e0b58a565c135d7ff90440c335 | Bits           |
+-----------------------------+----------------------------------+----------------+
2 rows in set (0.00 sec)

files in attachment
[pl.zip](https://github.com/xmacan/plugin_topx/files/3307218/pl.zip)

**Comment by xmacan** [comment]
It seems that problem is in decimal(20,6). It is too small. Please try:
 alter table  plugin_topx_average modify value1 decimal(28,6) not null default '0.000000';
 alter table  plugin_topx_average modify value2 decimal(28,6) not null default '0.000000';
 alter table  plugin_topx_average modify result_value decimal(30,6) not null default '0.000000';

Old data remains bad. New data sholud be better.

Please let me know, if it helps

**Comment by maxstech** [comment]
This helped to show high values.
But it seems to me, I do not see the correct data.
Here compare my graphics and topx data. Too large values.
for example:
![incorr](https://user-images.githubusercontent.com/47040342/60017542-9eca6780-9691-11e9-95d9-a6d1ae34a7f3.jpg)

In the output settings I set:

db_execute ("INSERT INTO plugin_topx_source (sorting,dt_name,hash,operation,unit,final_operation,final_unit,final_number) values ('desc','Interface - traffic','6632e1e0b58a565c135d7ff90440c335','traffic_in+traffic_out','**Bits','/','bit/Kbit/Mbit','1/1000/1000000')");**

**Comment by xmacan** [comment]
please try to disable->uninstall->install-> enable topx plugin. It will delete all topx data. I have seen this before. 
Please let me know if data are better

**Comment by maxstech** [comment]
"try to disable->uninstall->install-> enable topx plugin." -  I did it right after I changed the decimal (x) values and only then I got new data.

**Comment by xmacan** [comment]
Ok, thank you for your message.
TopX code is old and definitely not the best. My code is doing the same thing like DSstat. I decided implement Cacti's DSstat. I expect first version in few days.

**Comment by xmacan** [comment]
I implemented Cacti's DSStats. Please try now. Interface statistics are fine now. Old version displays in bits, new version in bytes!

Please let me know

**Comment by maxstech** [comment]
I removed the old plugin and put a new, included dsstats but does not work:

![ds1](https://user-images.githubusercontent.com/47040342/60437226-9389b580-9c16-11e9-9708-7d8cb729d91a.jpg)
![ds2](https://user-images.githubusercontent.com/47040342/60437233-9a182d00-9c16-11e9-8d11-6157eb7505fb.jpg)
![ds3](https://user-images.githubusercontent.com/47040342/60437250-a00e0e00-9c16-11e9-9a69-68085e908299.jpg)



2019/07/01 15:33:44 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/topx/topx.php[251]:CactiErrorHandler())
--
2019/07/01 15:33:44 - ERROR PHP WARNING in Plugin 'topx': Invalid argument supplied for foreach() in file: /opt/cacti/plugins/topx/topx.php on line: 251
2019/07/01 15:33:44 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS t2 ON t1.local_data_id = t2.local_data_id WHERE t1.data_template_id = 2 ORDER' at line 1
2019/07/01 15:33:44 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS t2 ON t1.local_data_id = t2.local_data_id WHERE t1.data_template_id = 2 ORDER' at line 1
2019/07/01 15:33:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/topx/topx.php[251]:CactiErrorHandler())

**Comment by xmacan** [comment]
Please uncomment line 236: // print $columns . ' ' . $query;
It will displays SQL query. Try this query (prepend word SELECT) in SQL client and send result to me.

**Comment by xmacan** [comment]
Which Cacti version do you have?

**Comment by maxstech** [comment]
i use cacti 124

**Comment by xmacan** [comment]
And SQL query above?

**Comment by maxstech** [comment]
can be on much detail what request03.07.2019, 17:42, "Petr Macek" <notifications@github.com>:And SQL query above?

**Comment by maxstech** [comment]
on line 236 i see: 
//list($micro,$seconds) = split(" ", microtime());   i uncommented it

2019/07/03 18:01:21 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
2019/07/03 18:01:19 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
2019/07/03 18:01:11 - CMDPHP ERROR: A DB Exec Failed!, Error: PDOStatement::execute(): send of 5497 bytes failed with errno=32 Broken pipe

**Comment by xmacan** [comment]
Be careful - you changed setup.php instead of topx.php! And you probably changed old topx code because new version has less lines. Try:
1) disable, deinstall topx in Cacti console
2) remove topx directory in your cacti_installation/plugins
3) download actual version from https://github.com/xmacan/plugin_topx/archive/master.zip
4) unpack, rename to topx and copy to cacti_installation/plugins
5) install, enable in Cacti console

If you still have problem uncomment line 236 in topx:
// print $columns . ' ' . $query;
It will displays SQL query. Try this query (prepend word SELECT) in SQL client and send result to me.

**Comment by maxstech** [comment]
sql-query:

t1.local_data_id as local_data_id, concat(t1.name_cache,' - ', t2.rrd_name) as name, t2.average as value, t2.peak as peak FROM data_template_data AS t1 LEFT JOIN data_source_stats_hourly AS t2 ON t1.local_data_id = t2.local_data_id WHERE t1.data_template_id = 1 ORDER BY t2.average ASC LIMIT 5

![error top](https://user-images.githubusercontent.com/47040342/60675753-cc7b9180-9e85-11e9-8ecc-10139cd20a64.jpg)
![error top2](https://user-images.githubusercontent.com/47040342/60675999-6e9b7980-9e86-11e9-8603-fa1f55a0efbd.jpg)

**Comment by xmacan** [comment]
few bugs fixed, please try develop version

**Comment by maxstech** [comment]
Now data there is. But they are incorrect
![topx актуал](https://user-images.githubusercontent.com/47040342/62299652-05575800-b47e-11e9-9197-4ee3b07a8f12.jpg)

**Comment by xmacan** [comment]
Is it from "Last hour" or longer interval (day, week, ...)?

Please try check last day. I have similar strange result with "last hour" interval

**Comment by xmacan** [comment]
Please try now - version 0.6
