### ISSUE TITLE
Plugin not installed correctly - Cacti 1.2.13

### ISSUE THREAD

**Issue by cacti-user** [xmacan/plugin_topx#4]
Hi mate,

Thanks for making this plugin, looks great. However, I have not been able to install it with cacti 1.2.13. After installation getting this error when clicking on TopX tab
![image](https://user-images.githubusercontent.com/68411536/91933638-84802500-ed3d-11ea-91b6-4dfa75f18d76.png)

There are no errors or logs in the log file about this plugin. Checked DB and it's not even creating SQL tables

**Comment by streaker-silent** [comment]
Getting the same issue on Cacti 1.2.11

**Comment by xmacan** [comment]
It is strange. I have tested it with cacti 1.2.12 and 1.3.0. It is working without any error. 
Which database and version have you got?
Is it something interesting in web server log?

**Comment by cacti-user** [comment]
I am using 5.5.65-MariaDB, there are no logs or errors in apache logs either. However, I tried 0.4 version and that gets installed and shows the tab, but as you mentioned there is a huge difference between 0.4 and 0.5

**0.4 Topx**
![image](https://user-images.githubusercontent.com/68411536/92662258-8efc7900-f352-11ea-885e-ac4d09b60dda.png)

**Comment by xmacan** [comment]
TopX 0.5 hasn't any sql table. Try to enable Configuration -> settings -> Data -> Enable Data Source Statistics Collection

**Comment by streaker-silent** [comment]
> 
> 
> It is strange. I have tested it with cacti 1.2.12 and 1.3.0. It is working without any error.
> Which database and version have you got?
> Is it something interesting in web server log?

[Thu Sep 10 14:34:06.771789 2020] [:error] [pid 2742] [client 105.185.165.26:60406] PHP Parse error:  syntax error, unexpected '[' in /usr/share/cacti/plugins/topx/topx.php on line 49, referer: http://105.226.1.200/cacti/clog.php?rfilter=dG9weA%3D%3D&reverse=1&refresh=60&message_type=-1&tail_lines=500&filename=cacti_stderr.log&

which points to:        return round($size, [2,2,2,2,2,3,3,4,4][$i]).[' ','k','M','G','T','P','E','Z','Y'][$i];

**Comment by xmacan** [comment]
great, I will fix it. Which PHP version have you got? I seems that you are using very old PHP like 5.4

**Comment by xmacan** [comment]
Please try new code

**Comment by cacti-user** [comment]
Thank you very much, yes I am still using 5.4 unfortunately. 
This seems to have fixed the issue for me :)

**Comment by cacti-user** [comment]
A quick question sorry, If I want to see the results in bits/sec, is there an easy way to see it?

**Comment by xmacan** [comment]
Where? Please show screenshot

**Comment by cacti-user** [comment]
It's showing different results in the database. If I look at the results directly from the data_source_stats tables for daily stats and convert it in bits/sec the peak interfaces are
![image](https://user-images.githubusercontent.com/68411536/92872087-c144ce00-f459-11ea-9055-89b644147ea9.png)

but in TopX, top interfaces are
![image](https://user-images.githubusercontent.com/68411536/92872255-ed604f00-f459-11ea-8483-48beb1bb0c0b.png)

**Comment by xmacan** [comment]
hmmm, it seems that topx has big error. I have to look at it. Please wait

**Comment by cacti-user** [comment]
Any luck with this Petr?

**Comment by xmacan** [comment]
You have to wait for few days. I'm working on big changes. I'm returning back function from v. 0.4 now. After it I will try solve others.

**Comment by xmacan** [comment]
done, please try actual 0.6 version. There was problem bits/bytes

**Comment by xmacan** [comment]
Please let me know if it working well now. Thank you

**Comment by cacti-user** [comment]
Oh great news, thank you. Will test and provide feedback
