### ISSUE TITLE
Dec 1 2021 commits break the topx graphs display if using more than Top 5 display

### ISSUE THREAD

**Issue by jdcoats** [xmacan/plugin_topx#6]
![image](https://user-images.githubusercontent.com/42470924/147834119-5f9d0b66-1f96-445d-891d-7dce8f3b5d9f.png)

![image](https://user-images.githubusercontent.com/42470924/147834125-ae4cff47-82f7-40b1-983a-1f53407ecbd9.png)

**Comment by xmacan** [comment]
I cannot reproduce this. I can see the chart even if I set 20 or 50 records. Until now it was possible display graph for all records. That could be problematic for more records. I decided to disable this now. Graph will be displayed only for 50 or less records.

Back to your issue - Have you this issue with all datasources or only with Traffic in+Traffic out? Please send me source code of page where graph is missing

**Comment by jdcoats** [comment]
[view-source_topx.zip](https://github.com/xmacan/plugin_topx/files/7803767/view-source_topx.zip)
it is happening on multiple DS's in multiple browsers.

**Comment by jdcoats** [comment]
okay, more info. If I select 10,20,50 the graph does not render, if I click the "Go" button at least twice it will render.

**Comment by jdcoats** [comment]
It works fine in Firefox. The problem is Chromium specific I guess. Issue happens in Chrome and Edge.

**Comment by xmacan** [comment]
great, I tested that only in firefox. I will look at it in chrome later

**Comment by xmacan** [comment]
I have tested it in Edge and Chrome and it works fine. Maybe any issue with specific chrome/edge version.
Can you test it again, please?

**Comment by jdcoats** [comment]
i can confirm that this issue no longer exists. I can only assume another Chrome update fixed it.
