### ISSUE TITLE
Cacti 1.2.21 : "Plugin 'topx': Division by zero" in Cacti logs

### ISSUE THREAD

**Issue by iskandarbasman** [xmacan/plugin_topx#7]
TOPX plugin seems to be working correctly but I see this following error in the cacti logs.

![image](https://user-images.githubusercontent.com/67727557/197167785-a3ef7013-03a7-467c-80d5-04b7874b247b.png)

**Comment by xmacan** [comment]
Has been fixed before ... Please try release 0.7 or actual Master branch
