### ISSUE TITLE
GIT Release 0.7 the correct version ?

### ISSUE THREAD

**Issue by iskandarbasman** [xmacan/plugin_topx#8]
Download and tried to install release topx release 0.7 from GIT but the version in Cacti plugins shows version 0.6 still.
Check INFO file and see it states version 0.6.

![image](https://user-images.githubusercontent.com/67727557/201561478-646d6fc0-d82b-4fd0-b598-02c3ad336614.png)

**Comment by xmacan** [comment]
thank you, fixed
